// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsdaCiHICk5rjmfvANs5lh4wsHCMJ9IxM',
    appId: '1:527913812670:web:3ef2930004f1c03f5214ef',
    messagingSenderId: '527913812670',
    projectId: 'adani-website',
    authDomain: 'adani-website.firebaseapp.com',
    storageBucket: 'adani-website.appspot.com',
    measurementId: 'G-QNQ0X55TMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEb9cQ93Kg_Xh9_3CW-TlwGvf567GQEms',
    appId: '1:527913812670:android:2430af998782f74b5214ef',
    messagingSenderId: '527913812670',
    projectId: 'adani-website',
    storageBucket: 'adani-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2DKU6KLQAkRCRyyQ7CDqoTQKp6NmFauw',
    appId: '1:527913812670:ios:8041ed4ff2451e085214ef',
    messagingSenderId: '527913812670',
    projectId: 'adani-website',
    storageBucket: 'adani-website.appspot.com',
    iosClientId: '527913812670-c4hgucv0of8hp33247fbv0c77oqbacqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.adani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2DKU6KLQAkRCRyyQ7CDqoTQKp6NmFauw',
    appId: '1:527913812670:ios:8041ed4ff2451e085214ef',
    messagingSenderId: '527913812670',
    projectId: 'adani-website',
    storageBucket: 'adani-website.appspot.com',
    iosClientId: '527913812670-c4hgucv0of8hp33247fbv0c77oqbacqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.adani',
  );
}
